title: Notes
description: >-
  Michael McIntyre's Second Brain
permalink: pretty
# just the docs config
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
footer_content: "Copyright &copy; 2021 Michael McIntyre. "
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
# gh_edit_repository: "https://github.com/" # the github URL for your repo
# gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "edit"

# comment out theme if deploying, or use theme for local
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: custom-dark
url: "https://itsmynotes.com"
baseurl: ""
repository: mmcintyre1/its-my-notes

plugins:
  - jekyll-seo-tag
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-spaceship

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - vendor
  - Makefile
  - spare_thoughts
  - templates
  - scripts
  - todo.md

titles_from_headings:
  enabled: true
  strip_title: false
  collections: false

aux_links:
  "My Second Brain on GitHub":
    - "https://github.com/mmcintyre1/my-second-brain"

ga_tracking: G-M6EEXPRNWS
ga_tracking_anonymize_ip: true

defaults:
  - scope:
      path: "tech_books"
    values:
      parent: Tech Books
      nav_exclude: true
  - scope:
      path: "business_books"
    values:
      parent: Business Books
      nav_exclude: true
  - scope:
      path: "educational_books"
    values:
      parent: Educational Books
      nav_exclude: true
  - scope:
      path: "other_books"
    values:
      parent: Other Books
      nav_exclude: true
  - scope:
      path: "articles"
    values:
      parent: Articles
      nav_exclude: true
  - scope:
      path: "classes"
    values:
      parent: Classes
      nav_exclude: true
  - scope:
      path: "quotes"
    values:
      parent: Quotes
      nav_exclude: true
  - scope:
      path: "vocabulary"
    values:
      parent: Vocabulary
      nav_exclude: true
  - scope:
      path: "projects"
    values:
      parent: Projects
      nav_exclude: true
  - scope:
      path: "podcasts"
    values:
      parent: Podcasts
      nav_exclude: true
