version: "3.7"

services:
  jekyll:
    image: jekyll/jekyll
    command: jekyll serve --watch --force_polling --incremental --config _config.yml,_config_dev.yml
    environment:
      - JEKYLL_ENV=docker
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
