title: Notes
description: >-
  Michael McIntyre reading notes
permalink: pretty
baseurl: /reading-notes

plugins:
  - jekyll-seo-tag
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

remote_theme: pmarsceill/just-the-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

color_scheme: custom

aux_links:
  "Learning Notes on GitHub":
    - "//github.com/"

# Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub."
# gh_edit_repository: "" # the github URL for your repo
# gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "edit"

defaults:
  - scope:
      path: "books"
    values:
      parent: Books
      nav_exclude: false