title: Notes
description: >-
  Michael McIntyre Reading Notes
permalink: pretty

baseurl: /reading-notes
url: https://mmcintyre1.github.io

color_scheme: custom

plugins:
  - jekyll-seo-tag
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-remote-theme

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# comment out theme if deploying, or use theme for local
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs@v0.2.8

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

color_scheme: custom

aux_links:
  "Reading Notes on GitHub":
    - "https://github.com/mmcintyre1/reading-notes"

# Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub."
# gh_edit_repository: "https://github.com/keyvanakbary/learning-notes" # the github URL for your repo
# gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "edit"

defaults:
  - scope:
      path: "articles"
    values:
      parent: Articles
      nav_exclude: true
  - scope:
      path: "books"
    values:
      parent: Books
      nav_exclude: true
  - scope:
      path: "talks"
    values:
      parent: Talks
      nav_exclude: true
  - scope:
      path: "papers"
    values:
      parent: Papers
      nav_exclude: true