title: Notes
description: >-
  Michael McIntyre Reading Notes
permalink: pretty

# just the docs config
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2021 Michael McIntyre. "
# comment out theme if deploying, or use theme for local
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: custom-dark
baseurl: /reading-notes
url: https://mmcintyre1.github.io

plugins:
  - jekyll-seo-tag
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-spaceship

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

aux_links:
  "Reading Notes on GitHub":
    - "https://github.com/mmcintyre1/reading-notes"

# Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub."
# gh_edit_repository: "https://github.com/keyvanakbary/learning-notes" # the github URL for your repo
# gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "edit"

defaults:
  - scope:
      path: "tech_books"
    values:
      parent: Tech Books
      nav_exclude: true
  - scope:
      path: "business_books"
    values:
      parent: Business Books
      nav_exclude: true
  - scope:
      path: "other_books"
    values:
      parent: Other Books
      nav_exclude: true
  - scope:
      path: "classes"
    values:
      parent: Classes
      nav_exclude: true
  - scope:
      path: "quotes"
    values:
      parent: Quotes
      nav_exclude: true
