
version: '3.7'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll serve --watch --force_polling
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ../books:/srv/jekyll/books