version: '3.7'

services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll serve --watch --force_polling --config _config.yml,_config_dev.yml
    environment:
    - JEKYLL_ENV=docker
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ../tech_books:/srv/jekyll/tech_books
      - ../tech_books:/srv/jekyll/other_books
