source "https://rubygems.org"

gem "jekyll"
gem "just-the-docs"
gem "kramdown-parser-gfm"
gem 'github-pages'

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jekyll-spaceship'
  gem "jekyll-default-layout"
  gem "jekyll-optional-front-matter"
  gem "jekyll-titles-from-headings"
  gem "jekyll-feed"
  gem "jekyll-remote-theme"
end