source "https://rubygems.org"

gem "jekyll"
gem "just-the-docs"
gem "kramdown-parser-gfm"
gem "jekyll-default-layout"
gem "jekyll-optional-front-matter"
gem "jekyll-titles-from-headings"
gem "github-pages"