source "https://rubygems.org"

gem "jekyll", "~> 3.3"
gem "just-the-docs"
gem "kramdown-parser-gfm"
gem "jekyll-default-layout"
gem "jekyll-optional-front-matter"
gem "jekyll-titles-from-headings"
gem "jekyll-feed"
gem "jekyll-remote-theme"
gem 'jekyll-spaceship'
gem 'github-pages', group: :jekyll_plugins